version: "3.8"

services:
  proxy:
    image: geometalab/env-configurable-caddy:latest
    environment:
      CADDY_CONFIG: |
        :8080 {
          route {
            handle /api/* {
              uri strip_prefix /api
              reverse_proxy backend:3010
            }
            redir /api /api/
            reverse_proxy /* {
              to frontend:80
            }
          }
        }
    networks:
      - web
      - default
    deploy:
      labels:
        caddy: cactus-dev.sifs0003.infs.ch
        caddy.reverse_proxy: "{{upstreams 8080}}"
      restart_policy:
        condition: "on-failure"
    

  frontend:
    image: $CONTAINER_REGISTRY_PATH/frontend:dev
    environment:
      - REACT_APP_BACKEND_BASE_URI=https://cactus-dev.sifs0003.infs.ch/api
    networks:
      - default
    deploy:

      restart_policy:
        condition: "on-failure"

  backend:
    image: $CONTAINER_REGISTRY_PATH/backend:dev
    environment:
      #- FRONTEND_ORIGIN=${FRONTEND_PROTOCOL}://${FRONTEND_HOST}:${FRONTEND_PORT}
      - PORT=3010
      - DATABASE_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@database:27017/cactus
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - FRONTEND_ORIGIN=https://cactus-dev.sifs0003.infs.ch
      - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
      - GITHUB_OAUTH_CALLBACK_BASE_URL=https://cactus-dev.sifs0003.infs.ch/api
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_CALLBACK_BASE_URL=https://cactus-dev.sifs0003.infs.ch/api
      - SWAGGER_BASE_PATH=/api
    networks:
      - web
      - default
    deploy:
      restart_policy:
        condition: "on-failure"

  database:
  # *portainer: mongodump --username tester -d cactus --out /backup/
  # *portainer: mongodump --username tester -d cactus --archive=/backup/1.archive
    image: mongo:6.0.4-focal
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - cactus-database:/data/db
      - cactus-database-backup:/backup
    deploy:
      restart_policy:
        condition: "on-failure"

volumes:
  cactus-database: null
  cactus-database-backup: null

networks:
  web:
    external: true
    name: web
