version: '3.8'

services:
  #frontend:
  #  image: $CONTAINER_REGISTRY_PATH/smart-factory/techpark/ipc/sap-proxy/stable:latest
  #  environment:
  #    - REACT_APP_FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
  #    - REACT_APP_FRONTEND_HOST=${FRONTEND_HOST}
  #    - REACT_APP_FRONTEND_PORT=${FRONTEND_PORT}
  #    - REACT_APP_BACKEND_PROTOCOL=${BACKEND_PROTOCOL}
  #    - REACT_APP_BACKEND_HOST=${BACKEND_HOST}
  #    - REACT_APP_BACKEND_PORT=${BACKEND_PORT}
  #  networks:
  #    - web
  #    - default
  #  deploy:
  #    labels:
  #      caddy: sapproxy.sifs0003.infs.ch
  #      caddy.reverse_proxy: "{{upstreams $SERVICE_PORT}}"
  #    restart_policy:
  #      condition: "on-failure"
                
  backend:
    image: $CONTAINER_REGISTRY_PATH/backend:latest
    environment:
      - FRONTEND_ORIGIN=${FRONTEND_PROTOCOL}://${FRONTEND_HOST}:${FRONTEND_PORT}
      - API_HOST=${BACKEND_HOST}
      - API_PORT=5566
      - DB_HOST=database
      - DB_PORT=${CONTAINER_SERVICE_DB_PORT}
      - DB_NAME=${BACKEND_DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - web
      - default
    deploy:
      labels:
        caddy: cactus-api.sifs0003.infs.ch
        caddy.reverse_proxy: "{{upstreams 5566}}"
      restart_policy:
        condition: "on-failure"
        
  database:
    image: mongo:6.0.4-focal
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      restart_policy:
        condition: "on-failure"  
  
networks:
  web:
    external: true
    name: web
