version: "3.8"

services:
  frontend:
    image: $CONTAINER_REGISTRY_PATH/frontend:latest
    environment:
      - REACT_APP_BACKEND_BASE_URI=https://cactus-api.sifs0003.infs.ch/api
    networks:
      - web
    deploy:
      labels:
        caddy: cactus.sifs0003.infs.ch
        caddy.reverse_proxy: "{{upstreams 80}}"
      restart_policy:
        condition: "on-failure"

  backend:
    image: $CONTAINER_REGISTRY_PATH/backend:latest
    environment:
      #- FRONTEND_ORIGIN=${FRONTEND_PROTOCOL}://${FRONTEND_HOST}:${FRONTEND_PORT}
      - PORT=3010
      - DATABASE_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@database:27017/cactus
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - FRONTEND_ORIGIN=https://cactus.sifs0003.infs.ch
    networks:
      - web
      - default
    deploy:
      labels:
        caddy: cactus-api.sifs0003.infs.ch
        caddy.reverse_proxy: "{{upstreams 3010}}"
      restart_policy:
        condition: "on-failure"

  database:
    image: mongo:6.0.4-focal
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    deploy:
      restart_policy:
        condition: "on-failure"

networks:
  web:
    external: true
    name: web
