version: "3.8"

services:
  frontend:
    image: $CONTAINER_REGISTRY_PATH/frontend:sha256:e1d2c5c1ebcb5c6fc08c24085feef49a27c1041dc6e7025555892e3825c00c7e
    environment:
      - REACT_APP_BACKEND_BASE_URI=https://cactus-api.sifs0003.infs.ch/api
    networks:
      - web
    deploy:
      labels:
        caddy: cactus.sifs0003.infs.ch
        caddy.reverse_proxy: "{{upstreams 80}}"
      restart_policy:
        condition: "on-failure"

  backend:
    image: $CONTAINER_REGISTRY_PATH/backend:sha256:3386cae6e195fd9dd07b1e5f5843670f6a1bc773688fd8df67e6078a6c3a400b
    environment:
      #- FRONTEND_ORIGIN=${FRONTEND_PROTOCOL}://${FRONTEND_HOST}:${FRONTEND_PORT}
      - PORT=3010
      - DATABASE_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@database:27017/cactus
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - FRONTEND_ORIGIN=https://cactus.sifs0003.infs.ch
      - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
      - GITHUB_OAUTH_CALLBACK_BASE_URL=https://cactus-api.sifs0003.infs.ch/api
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_CALLBACK_BASE_URL=https://cactus-api.sifs0003.infs.ch/api

    networks:
      - web
      - default
    deploy:
      labels:
        caddy: cactus-api.sifs0003.infs.ch
        caddy.reverse_proxy: "{{upstreams 3010}}"
      restart_policy:
        condition: "on-failure"

  database:
  # *portainer: sh -c 'exec mongodump -d cactus --archive --out /backup/' > /some/path/on/your/host/all-collections.archive
    image: mongo:6.0.4-focal
    networks:
      - default
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - cactus-database:/data/db
      - cactus-database-backup:/backup
    deploy:
      restart_policy:
        condition: "on-failure"

volumes:
  cactus-database: null
  cactus-database-backup: null

networks:
  web:
    external: true
    name: web
